export const RailRoad_Ticket_ADDRESS = '0xD198C673580cd2Afda6B9993198D9067881457f6'

export const RailRoad_Card_ADDRESS = '0xa224d509a5244418B6F6583CDE4ba7F56E7cA504'

export const RailRoad_Ticket_ABI = [
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"base_price",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"cardContract",
            "type":"address"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"string",
            "name":"action",
            "type":"string"
         }
      ],
      "name":"adminEdit",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"ticketBuy",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"ticketUse",
      "type":"event"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"admin_revoke",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"admin_set",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"admins",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"calculate_ticket_price",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"card_contract_address",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"contract_owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"ticket_buy",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"ticket_price",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"ticket_use",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"tickets",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   }
]

export const RailRoad_Card_ABI = [
   {
      "inputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"string",
            "name":"action",
            "type":"string"
         }
      ],
      "name":"adminEdit",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"string",
            "name":"action",
            "type":"string"
         },
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"price",
            "type":"uint256"
         }
      ],
      "name":"cardBuySell",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"price",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"reduction",
            "type":"uint256"
         }
      ],
      "name":"cardCreate",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"address",
            "name":"receiver",
            "type":"address"
         }
      ],
      "name":"cardTransfer",
      "type":"event"
   },
   {
      "inputs":[
         {
            "internalType":"string",
            "name":"_name",
            "type":"string"
         },
         {
            "internalType":"uint256",
            "name":"_discountPercent",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_price",
            "type":"uint256"
         },
         {
            "internalType":"string",
            "name":"_description",
            "type":"string"
         },
         {
            "internalType":"string",
            "name":"_image_url",
            "type":"string"
         }
      ],
      "name":"addDiscountCard",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"admin_revoke",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"admin_set",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"admins",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_cardId",
            "type":"uint256"
         }
      ],
      "name":"buyDiscountCard",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"cardCounter",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"contract_owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"discountCards",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"id",
            "type":"uint256"
         },
         {
            "internalType":"string",
            "name":"name",
            "type":"string"
         },
         {
            "internalType":"uint256",
            "name":"discountPercent",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"available",
            "type":"bool"
         },
         {
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"price",
            "type":"uint256"
         },
         {
            "internalType":"string",
            "name":"description",
            "type":"string"
         },
         {
            "internalType":"string",
            "name":"image_url",
            "type":"string"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_userAddress",
            "type":"address"
         }
      ],
      "name":"getBiggestCard",
      "outputs":[
         {
            "components":[
               {
                  "internalType":"uint256",
                  "name":"id",
                  "type":"uint256"
               },
               {
                  "internalType":"string",
                  "name":"name",
                  "type":"string"
               },
               {
                  "internalType":"uint256",
                  "name":"discountPercent",
                  "type":"uint256"
               },
               {
                  "internalType":"bool",
                  "name":"available",
                  "type":"bool"
               },
               {
                  "internalType":"address",
                  "name":"owner",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"price",
                  "type":"uint256"
               },
               {
                  "internalType":"string",
                  "name":"description",
                  "type":"string"
               },
               {
                  "internalType":"string",
                  "name":"image_url",
                  "type":"string"
               }
            ],
            "internalType":"struct DiscountCards.DiscountCard",
            "name":"",
            "type":"tuple"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_userAddress",
            "type":"address"
         }
      ],
      "name":"getBiggestReduct",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"listAvailableCards",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_userAddress",
            "type":"address"
         }
      ],
      "name":"listUserCards",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_cardId",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_cardPrice",
            "type":"uint256"
         }
      ],
      "name":"putCardToSell",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_cardId",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_toAddress",
            "type":"address"
         }
      ],
      "name":"transferDiscountCard",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
]